# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Document

on:
  pull_request:
    branches: [master, main]
    types: [closed]
  push:
    branches: [master, main]

jobs:
  document:
    # https://stackoverflow.com/a/67833464
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run document

      - uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: automated documenting on PR
          branch: ${{ github.head_ref }}
